spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/graphviz
    username: postgres
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
springfox:
  documentation:
    swagger-ui:
      enabled: true
